name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: echo "Step one executed"
      - name: Exit Step
        run: echo "Step exited - Bye!!!"
  
